### ISSUE TITLE
一个BUG

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [bangbang93/BMCL#32]
某鱼的启动器废了，就来看看这启动器，但是版本解析貌似有bug
看图
http://i2.buimg.com/1949/73be334bb0b5b96d.png
卧槽我怎么又这么多个版本？
其实才这么几个
http://i2.buimg.com/1949/43910c3d332def22.png
而某鱼的启动器正常
http://i2.buimg.com/1949/c7317cf5aa4c3be5.png

顺带问下BMCL支不支持类似于BN与HMCL的版本隔离？就是除assets与library都保存在版本文件夹里的那种？

**Comment by bangbang93** [comment]
bmcl取的是json中的id字段作为版本名称，所以存在重复的问题，我过两天会把名称换回文件夹名称的方式
版本隔离最早其实是BMCL做的，但是在4.0重写启动核心之后我还没顾上实现版本隔离，这个功能最迟8月底会回归的。
