### ISSUE TITLE
不知道算不算一个BUG

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [bangbang93/BMCL#34]
新版本启动器出来后，第一时间下载并且放进自己的整合包里面
新创建了一个存档以后，跑跑路就关了MC，主要是看看新版本的一些特性
但是当重新打开BMCL后，发现BMCL会把版本号文件夹下的json文件都识别为一个新版本？
![uc 20160825112843](https://cloud.githubusercontent.com/assets/20567492/17955932/5579b0d4-6ab8-11e6-9eed-51518c927842.png)
![uc 20160825112850](https://cloud.githubusercontent.com/assets/20567492/17955933/557ab20e-6ab8-11e6-807d-dfe7c5982748.png)
一旦点击，BMCL就会崩溃
![uc 20160825112901](https://cloud.githubusercontent.com/assets/20567492/17955963/957ebe5e-6ab8-11e6-9476-2d06fe1f64e3.png)

> BMCL,4.5.0.1830
> mscorlib
> System.ArgumentNullException: String 引用没有设置为 String 的实例。
> 参数名: s
>    在 System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
>    在 BMCLV2.Windows.MainWindowTab.GridGame.listVer_SelectionChanged(Object sender, SelectionChangedEventArgs e)
>    在 System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    在 System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
>    在 System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
>    在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
>    在 System.Windows.Controls.Primitives.Selector.SetSelectedHelper(Object item, FrameworkElement UI, Boolean selected)
>    在 System.Windows.Controls.Primitives.Selector.NotifyIsSelectedChanged(FrameworkElement container, Boolean selected, RoutedEventArgs e)
>    在 System.Windows.Controls.Primitives.Selector.OnSelected(Object sender, RoutedEventArgs e)
>    在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    在 System.Windows.Controls.ListBoxItem.OnSelected(RoutedEventArgs e)
>    在 System.Windows.Controls.ListBoxItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
>    在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    在 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
>    在 System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
>    在 System.Windows.Controls.ListBox.NotifyListItemClicked(ListBoxItem item, MouseButton mouseButton)
>    在 System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(MouseButton mouseButton)
>    在 System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
>    在 System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
>    在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    在 System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
>    在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    在 System.Windows.Input.InputManager.ProcessStagingArea()
>    在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
> String 引用没有设置为 String 的实例。
> 参数名: s
> Key:System.Object
> Value:
>    在 System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
>    在 BMCLV2.Windows.MainWindowTab.GridGame.listVer_SelectionChanged(Object sender, SelectionChangedEventArgs e)
>    在 System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    在 System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
>    在 System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
>    在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
>    在 System.Windows.Controls.Primitives.Selector.SetSelectedHelper(Object item, FrameworkElement UI, Boolean selected)
>    在 System.Windows.Controls.Primitives.Selector.NotifyIsSelectedChanged(FrameworkElement container, Boolean selected, RoutedEventArgs e)
>    在 System.Windows.Controls.Primitives.Selector.OnSelected(Object sender, RoutedEventArgs e)
>    在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    在 System.Windows.Controls.ListBoxItem.OnSelected(RoutedEventArgs e)
>    在 System.Windows.Controls.ListBoxItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
>    在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    在 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
>    在 System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
>    在 System.Windows.Controls.ListBox.NotifyListItemClicked(ListBoxItem item, MouseButton mouseButton)
>    在 System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(MouseButton mouseButton)
>    在 System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
>    在 System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
>    在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    在 System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
>    在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    在 System.Windows.Input.InputManager.ProcessStagingArea()
>    在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

-----------------BMCL LOG----------------------

08/25/2016 11:42:26信息:BMCLNG Ver.4.5.0.1830正在启动
08/25/2016 11:42:26信息:加载F:\Minecraft我的世界\bmcl.xml文件
08/25/2016 11:42:26信息:Javaw: C:\Program Files\Java\jre1.8.0_91\bin\javaw.exe, Username: Aimee_Boy, Javaxmx: 1024, Login: 离线模式, LastPlayVer: 1.10.2-forge1.10.2-12.18.1.2073, ExtraJvmArg:  -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true, Lang: zh-cn, Passwd: System.Byte[], Autostart: False, Report: True, CheckUpdate: True, WindowTransparency: 1, DownloadSource: 0, PluginConfig: System.Collections.Generic.Dictionary`2[System.String,System.Object], Height: 720, Width: 1280, FullScreen: False, LaunchMode: Standalone
08/25/2016 11:42:26信息:加载默认配置
08/25/2016 11:42:26信息:无需更新
08/25/2016 11:42:32错误:BMCL,4.5.0.1830
mscorlib
System.ArgumentNullException: String 引用没有设置为 String 的实例。
参数名: s
   在 System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   在 BMCLV2.Windows.MainWindowTab.GridGame.listVer_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   在 System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
   在 System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   在 System.Windows.Controls.Primitives.Selector.SetSelectedHelper(Object item, FrameworkElement UI, Boolean selected)
   在 System.Windows.Controls.Primitives.Selector.NotifyIsSelectedChanged(FrameworkElement container, Boolean selected, RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.Selector.OnSelected(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.ListBoxItem.OnSelected(RoutedEventArgs e)
   在 System.Windows.Controls.ListBoxItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   在 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   在 System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   在 System.Windows.Controls.ListBox.NotifyListItemClicked(ListBoxItem item, MouseButton mouseButton)
   在 System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(MouseButton mouseButton)
   在 System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
String 引用没有设置为 String 的实例。
参数名: s
Key:System.Object
Value:
   在 System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   在 BMCLV2.Windows.MainWindowTab.GridGame.listVer_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   在 System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
   在 System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   在 System.Windows.Controls.Primitives.Selector.SetSelectedHelper(Object item, FrameworkElement UI, Boolean selected)
   在 System.Windows.Controls.Primitives.Selector.NotifyIsSelectedChanged(FrameworkElement container, Boolean selected, RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.Selector.OnSelected(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.ListBoxItem.OnSelected(RoutedEventArgs e)
   在 System.Windows.Controls.ListBoxItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   在 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   在 System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   在 System.Windows.Controls.ListBox.NotifyListItemClicked(ListBoxItem item, MouseButton mouseButton)
   在 System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(MouseButton mouseButton)
   在 System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

![Uploading UC截图20160825114404.png…]()

并且，我明明已经勾选了BMCL的各版本存档与Mods隔离，但是每一次关闭BMCL后重新进BMCL会发现那个勾还是没有勾选，但是却有勾选了的效果，并且再次勾选启动后市没有勾选的效果。
这点对于我这个做整合包的不是很好，对于新手可能更不好
并且，我已经设置了MC分辨率为1280x720，但是还是以默认分辨率启动
最后，原来我语死早

**Comment by bangbang93** [comment]
分辨率的问题好像是参数不支持了，我看看现在正版启动器是怎么处理的

**Comment by mgdgfbhevdyeh** [comment]
不知道什么时候有更新了一个版本
但是我想说版本独立貌似出了问题
无论我在各版本与存档隔离那里打不打勾都是在没有分隔的清空下启动的

**Comment by mgdgfbhevdyeh** [comment]
新版本的版本独立貌似又出来问题。
已经勾选了各版本mod与存档独立
但还是没有用。

**Comment by mgdgfbhevdyeh** [comment]
感觉现在版本独立完全无效。
在versions下没有看到新的文件夹
versions/版本号下同样
确定已经勾选各版本mod与存档独立
之所以我这么断定，是因为我点击了打开资源包文件夹是.minecraft下的，不是versions下的

**Comment by bangbang93** [comment]
这次真是实现了一个新bug了……

**Comment by mgdgfbhevdyeh** [comment]
不会像偷懒的MOJANG一样叫特性或者移除次功能吧【手动滑稽

**Comment by bangbang93** [comment]
![image](https://cloud.githubusercontent.com/assets/3430784/18027224/18bdeba8-6c91-11e6-8141-02b29fb75b18.png)
我刚试了一下，我这里是正常的啊

**Comment by mgdgfbhevdyeh** [comment]
论坛那边也有人发帖了，Bangbang93你去看看你的BMCL论坛。

**Comment by bangbang93** [comment]
他和你情况又不一样，你发个启动之后的log过来我看看？

**Comment by mgdgfbhevdyeh** [comment]
现在我这边的版本隔离 BUG真实有规律出现（但在重装系统了之后至少能用了）
一次是隔离情况下启动的，一次是非隔离状态下启动的。

启动时我确定我只有在勾选一次各版本Mod与存档隔离才是以隔离的状态启动的
我确定在不是隔离状态启动的情况下那个勾是勾着的，而是隔离状态下启动的那个勾是没有勾着我自己勾一次才行
还有在我关闭了没有在隔离情况下启动的游戏之后，重新弹出来的窗口下各版本Mod与存档独立的勾不是勾着的
所以我认为如果BUG成立就应该是配置文件或者配置文件加载or修改的问题（感觉语言表达能力越来越差）

log我直接放百度里了http://pan.baidu.com/s/1jHWv7JS

**Comment by mgdgfbhevdyeh** [comment]
PS：发现点击Mod管理、Mod独立文件夹、Mod设置管理貌似都是在.minecraft\versions\版本号下的，不是.minecraft\versions\版本号\.minecraft下的文件夹。
还有Mod独立文件夹貌似没有用，试过把小地图生成的文件夹放进去结果卵用也没。
