### ISSUE TITLE
1840版本各版本存档和mod独立选项配置会莫名重置

### ISSUE THREAD

**Issue by cocakuma** [bangbang93/BMCL#37]
勾选各版本存档和mod独立选项，保存配置，然后关闭BMCL。再次打开BMCL，这时候可以看到各版本存档和mod独立选项这个选项是勾选的，点开始启动游戏。游戏启动后发现放在独立文件里的mod没有生效。打开bmcl.xml可以看到 LaunchMode被重置为了Normal。下次再打开BMCL，可以看到这个选项是没有勾选的。
推测应该是点启动游戏的时候，保存了一次配置，但是这个选项的配置，没有从UI上获取当前的勾选状态，而是被重置了

**Comment by bangbang93** [comment]
应该和#34是一个情况，等我下班回去查查

**Comment by mgdgfbhevdyeh** [comment]
@bangbang93 你查了多久了... ...

**Comment by bangbang93** [comment]
我这边刚试了一下……没出问题……
