### ISSUE TITLE
BMCL不能导入游戏吗？邮箱验证一直过不了

### ISSUE THREAD

**Issue by GKsnc** [bangbang93/BMCL#44]
只能在启动器里下载，或者将游戏移动到同目录里的.minecraft文件里

不支持选择.minecraft路径，是吗？

PS.我已经点过激活邮件了，右下角还是会提示让我确认。（再点击邮件提示已验证‘网址不存在或已过期’）

**Comment by bangbang93** [comment]
是
你是指www.bangbang93.com的邮箱验证过不了吗？

**Comment by xfl03** [comment]
论坛bug
- 注册[bangbang93.forum()](https://www.bangbang93.com)
- 在邮箱点击验证邮件中的链接`https://auth.bangbang93.com/mail/verify/UUID`
- 论坛中显示仍未确认邮箱
![图](https://i.loli.net/2019/10/22/jBqQmcI3hEFoUrW.png)

**Comment by bangbang93** [comment]
似乎是auth服务的邮箱认证状态没同步进论坛里……去论坛里的用户设置认证下邮箱试试，我研究一下这玩意

**Comment by GKsnc** [comment]
是的。设置里再次点确认邮件，邮箱里也没有在收到新的“验证邮件”。

**Comment by bangbang93** [comment]
这下应该可以用了……似乎是nodebb升级后和电子邮件发送方式的配置修改了

**Comment by GKsnc** [comment]
嗯，好了，谢谢

**Comment by TSStudio** [comment]
@bangbang93 记得close issue
