### ISSUE TITLE
java.io.IOException: Remote library forge has no version 36.2.20

### ISSUE THREAD

**Issue by QingShuiMuYang** [bangbang93/BMCL#50]
请您更新一下forge库，1.16.5的整合包更新需要。麻烦您了

**Comment by bangbang93** [comment]
MCBBS源和BMCLAPI源均已完成同步

另：
这是BMCL的Repo，bmclapi相关问题，可以去
<https://www.bangbang93.com/category/6/bmclapi>
哪怕再不济，也可以在OpenBMCLAPI
<https://github.com/bangbang93/openbmclapi>
