### ISSUE TITLE
I want to ask a question about whether he's breaking the law. 

### ISSUE THREAD

**Issue by BANSAFAn** [bangbang93/BMCL#52]
Good day ! I would like to find out if the BMCL API system violates github & microsoft policy 

There has just been a huge number of people who claim that you are breaking the law there and you are fucked, I'd rather keep silent

And I really wanted to hear the answer.

**Comment by xmzh0603** [comment]
f0ck u

**Comment by wuliaodexiaoluo** [comment]
玩原神玩的
